### ISSUE TITLE
permanent freezes

### ISSUE THREAD

**Issue by slowiu06** [kreezxil/better-than-minecolonies-getting-started#16]
I'm getting permanent freezes randomly after few minutes of playing. There is no crash log.
Already tried:
- updating Java
- updating GPU driver
- reinstalling modpack
- using other launcher

**Comment by kreezxil** [comment]
yes, it's gonna be in your latest.log now

we're having similar issues on WODNA.

Here's an example of how to do the crash reports because the latest.log is
going to be over 20mb

open it and scroll back to find the repeating java error. excerpt one block
of it and enclose in triple back ticks. then save file to your cloud drive
and paste the public share link

https://github.com/ldtteam/minecolonies/issues/4050

**Comment by slowiu06** [comment]
It is my latest log. 
https://gist.github.com/slowiu06/57909dce6d458ef675baa3e5d31531fc

**Comment by kreezxil** [comment]
i've isolated the issue with the WODNA team. it's FORGE 81+, today's patch fixes this.
