### ISSUE TITLE
Still glowing effect without The Endergetic Expansion mod

### ISSUE THREAD

**Issue by GuitarMoshi** [kreezxil/better-than-minecolonies-getting-started#27]
I just installed this modpack today and am seeing the glowing effect on mobs, but only after I've traveled several hundred blocks from spawn. I've double-checked and I do not have the Endergetic mod in question installed with the pack. The glow is causing severe lag. Any thoughts on what other mod or config setting may be causing it? I can't seem to turn off mob glow with the /effect command either.

Update: after playing a bit more it seems like the glowing effect on mobs is rarer than I thought. It seems to be centered around specific areas of the map, but I haven't figured out what's significant about it yet. I'll post more if I find more info.

**Comment by kreezxil** [comment]
how do you know that the glow is causing severe lag?

Thanks for the report, we'll add The Endergetic Expansion back to the pack.

**Comment by GuitarMoshi** [comment]
When I encounter mobs with the glow effect, my FPS drops to about 5. If I immediately turn around so no glowing mobs are visible, even if other mobs are also visible, my FPS goes back up to 40-50. I don't have the best gfx hardware so I never expect full 60FPS when playing modded, but that's a pretty significant FPS drop. If not for that the pack is fully playable. My guess is dropping render distance would help since it's showing some underground mobs, but there's just as many above-ground mobs depending on my view angle and the issue is the same.

I'll spend some time today in creative digging around this map and see if there's something in common in each glowing mob area that points me to a specific mod causing this. I've never seen this in a modpack before so I really don't know where to start looking.

**Comment by kreezxil** [comment]
it's baffling me too. I've done the binary search method to several times
to find it. It feels like a mod incompatibility.

Binary Search Method:
1. cut the modpack in half
2. load each half
3. the half that glowed, go back to #1 on
4. you should be left with the mod that is doing it

problem is that at a certain point everything stops glowing, it's like mod
has the ability to detect the amount of other mods loaded and if not enough
are loaded it stops glowing as if to say "they're looking for me, i'll
hide". When I find this mod, i'm going to start an aggressive campaign to
make sure it never gets installed in another mod pack ever again. Also
report it because as far as I am concerned and the many who have reported
this issue, it's a problem.

**Comment by kreezxil** [comment]
found it, it's a bug in Forbidden Arcanus. Others have found it too. The Mod author seems unwilling to patch his mod. https://github.com/stal111/Forbidden-Arcanus/issues/48

As of today FA is being removed from the pack.

**Comment by GuitarMoshi** [comment]
Thanks for tracking this one down. Much appreciated! Looking forward to jumping back into this pack.

**Comment by kreezxil** [comment]
I'm planning on bringing this forward to 1.15.2 today.
